//! English Auction contract — ascending bid auction.
//!
//! An ascending-price auction where participants submit bids that must exceed
//! the current highest bid by at least a minimum increment. The highest bidder
//! wins the asset when the auction expires, while outbid amounts are refunded.
//!
//! Generated by [soroban-forge](https://github.com/soroban-forge-labs/soroban-forge).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, token, Address, Env};

#[contracttype]
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum AuctionState {
    Open,
    Settled,
    Canceled,
}

#[contracttype]
pub enum DataKey {
    Seller,
    AssetToken,
    PaymentToken,
    AssetAmount,
    MinBid,
    MinIncrement,
    EndTime,
    HighestBidder,
    HighestBid,
    State,
}

#[contract]
pub struct EnglishAuctionContract;

#[contractimpl]
impl EnglishAuctionContract {
    /// Initialize an English auction and deposit the seller's asset into the contract.
    pub fn initialize(
        env: Env,
        seller: Address,
        asset_token: Address,
        payment_token: Address,
        asset_amount: i128,
        min_bid: i128,
        min_increment: i128,
        end_time: u64,
    ) {
        if env.storage().instance().has(&DataKey::Seller) {
            panic!("already initialized");
        }
        seller.require_auth();
        assert!(asset_amount > 0, "asset_amount must be positive");
        assert!(min_bid > 0, "min_bid must be positive");
        assert!(min_increment > 0, "min_increment must be positive");
        assert!(
            end_time > env.ledger().timestamp(),
            "end_time must be in the future"
        );

        // Transfer asset to contract
        let client = token::Client::new(&env, &asset_token);
        client.transfer(&seller, &env.current_contract_address(), &asset_amount);

        let s = env.storage().instance();
        s.set(&DataKey::Seller, &seller);
        s.set(&DataKey::AssetToken, &asset_token);
        s.set(&DataKey::PaymentToken, &payment_token);
        s.set(&DataKey::AssetAmount, &asset_amount);
        s.set(&DataKey::MinBid, &min_bid);
        s.set(&DataKey::MinIncrement, &min_increment);
        s.set(&DataKey::EndTime, &end_time);
        s.set(&DataKey::HighestBid, &0_i128);
        s.set(&DataKey::State, &AuctionState::Open);
    }

    /// Place a bid in payment tokens.
    pub fn bid(env: Env, bidder: Address, amount: i128) {
        bidder.require_auth();

        let s = env.storage().instance();
        let state: AuctionState = s.get(&DataKey::State).expect("not initialized");
        assert_eq!(state, AuctionState::Open, "auction is not open");

        let end_time: u64 = s.get(&DataKey::EndTime).unwrap();
        assert!(
            env.ledger().timestamp() < end_time,
            "auction has ended"
        );

        let highest_bid: i128 = s.get(&DataKey::HighestBid).unwrap();
        let min_bid: i128 = s.get(&DataKey::MinBid).unwrap();
        let min_inc: i128 = s.get(&DataKey::MinIncrement).unwrap();

        if highest_bid == 0 {
            assert!(amount >= min_bid, "bid below minimum");
        } else {
            assert!(
                amount >= highest_bid + min_inc,
                "bid does not meet minimum increment"
            );
        }

        let payment_token: Address = s.get(&DataKey::PaymentToken).unwrap();
        let client = token::Client::new(&env, &payment_token);

        // Refund previous bidder if any
        if highest_bid > 0 {
            let prev_bidder: Address = s.get(&DataKey::HighestBidder).unwrap();
            client.transfer(
                &env.current_contract_address(),
                &prev_bidder,
                &highest_bid,
            );
        }

        // Transfer new bid from bidder to contract
        client.transfer(&bidder, &env.current_contract_address(), &amount);

        s.set(&DataKey::HighestBidder, &bidder);
        s.set(&DataKey::HighestBid, &amount);
    }

    /// Settle the auction after end_time.
    pub fn settle(env: Env) {
        let s = env.storage().instance();
        let state: AuctionState = s.get(&DataKey::State).expect("not initialized");
        assert_eq!(state, AuctionState::Open, "auction not open");

        let end_time: u64 = s.get(&DataKey::EndTime).unwrap();
        assert!(
            env.ledger().timestamp() >= end_time,
            "auction has not ended"
        );

        let seller: Address = s.get(&DataKey::Seller).unwrap();
        let asset_token: Address = s.get(&DataKey::AssetToken).unwrap();
        let asset_amount: i128 = s.get(&DataKey::AssetAmount).unwrap();
        let asset_client = token::Client::new(&env, &asset_token);

        let highest_bid: i128 = s.get(&DataKey::HighestBid).unwrap();
        if highest_bid > 0 {
            let winner: Address = s.get(&DataKey::HighestBidder).unwrap();
            let payment_token: Address = s.get(&DataKey::PaymentToken).unwrap();
            let payment_client = token::Client::new(&env, &payment_token);

            // Transfer payment to seller
            payment_client.transfer(&env.current_contract_address(), &seller, &highest_bid);
            // Transfer asset to winner
            asset_client.transfer(&env.current_contract_address(), &winner, &asset_amount);
        } else {
            // No bids: return asset to seller
            asset_client.transfer(&env.current_contract_address(), &seller, &asset_amount);
        }

        s.set(&DataKey::State, &AuctionState::Settled);
    }

    /// Read highest bid amount.
    pub fn get_highest_bid(env: Env) -> i128 {
        env.storage()
            .instance()
            .get(&DataKey::HighestBid)
            .unwrap_or(0)
    }

    /// Read highest bidder address.
    pub fn get_highest_bidder(env: Env) -> Option<Address> {
        env.storage().instance().get(&DataKey::HighestBidder)
    }

    /// Read auction state.
    pub fn get_state(env: Env) -> Option<AuctionState> {
        env.storage().instance().get(&DataKey::State)
    }
}

#[cfg(test)]
mod test;
